version: '3'

services:
  stock-prediction:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./stock_prediction.db:/app/stock_prediction.db
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1